version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9865:9865 # qbittorrent
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - SERVER_COUNTRIES=Spain
      - TZ=ES

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=latest
      - TZ=ES
      - WEBUI_PORT=9865
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/Downloads/torrent:/downloads
    restart: unless-stopped
